"""Slide generation tool for LangGraph agents."""

import json

from langchain_core.tools import tool
from pydantic import BaseModel, Field

from app.services.pptx_gen import SlideDeck, pptx_generation_service
from app.core.logging import get_logger
from app.services.file_storage import file_storage_service

logger = get_logger(__name__)


# --- Structured output schema for LLM outline generation ---


class SlideElementSchema(BaseModel):
    """A single element on a slide."""

    type: str = Field(default="text", description="Element type: text or image")
    content: str = Field(description="Text content for the element")


class SlideSchema(BaseModel):
    """Specification for a single slide."""

    layout: str = Field(
        description="Slide layout: title_slide, section_header, content, two_column, or blank"
    )
    title: str = Field(description="Slide title")
    subtitle: str | None = Field(default=None, description="Subtitle (for title_slide)")
    elements: list[SlideElementSchema] = Field(
        default_factory=list, description="Slide content elements"
    )
    notes: str | None = Field(default=None, description="Speaker notes")
    image_prompt: str | None = Field(
        default=None,
        description="Description of a professional illustration for this slide",
    )


class SlideOutlineSchema(BaseModel):
    """Complete slide deck outline generated by the LLM."""

    title: str = Field(description="Presentation title")
    slides: list[SlideSchema] = Field(description="List of slides")


# --- Tool input schema ---


class GenerateSlideInput(BaseModel):
    """Input schema for slide generation tool."""

    topic: str = Field(description="Topic or description for the presentation to generate.")
    num_slides: int = Field(
        default=8,
        ge=4,
        le=20,
        description="Number of slides to generate (4-20).",
    )
    style: str = Field(
        default="professional",
        description="Visual style: professional, creative, minimal, or bold.",
    )
    include_images: bool = Field(
        default=False,
        description="Whether to generate images for slides.",
    )
    additional_context: str | None = Field(
        default=None,
        description="Additional context or requirements for the presentation.",
    )
    # Context fields (injected by agent, not provided by LLM)
    user_id: str | None = Field(
        default=None,
        description="User ID for storage (internal use only)",
        json_schema_extra={"exclude": True},
    )


@tool(args_schema=GenerateSlideInput)
async def generate_slides(
    topic: str,
    num_slides: int = 8,
    style: str = "professional",
    include_images: bool = False,
    additional_context: str | None = None,
    user_id: str | None = None,
) -> str:
    """Generate a PPTX presentation from a topic description using AI.

    Use this tool when the user asks you to:
    - Create a presentation or slide deck
    - Make PowerPoint slides about a topic
    - Generate a PPTX file

    The tool researches the topic, creates a structured outline using AI,
    and generates a professional PPTX file for download.

    Args:
        topic: Topic or description for the presentation
        num_slides: Number of slides (4-20, default 8)
        style: Visual style (professional, creative, minimal, bold)
        include_images: Whether to generate images for slides
        additional_context: Additional context or requirements
        user_id: User ID for storage (auto-injected by system)

    Returns:
        JSON string with download URL and presentation details
    """
    from app.agents.skills.builtin.slide_generation_skill import (
        STYLE_THEMES,
    )
    from app.ai.llm import llm_service
    from app.services.search import search_service

    logger.info(
        "generate_slides_tool_invoked",
        topic=topic[:100],
        num_slides=num_slides,
        style=style,
        user_id=user_id,
    )

    try:
        # Phase 1: Research
        research_context = ""
        sources = []
        try:
            results = await search_service.search_raw(
                query=topic,
                max_results=8,
                search_depth="advanced",
            )
            for r in results:
                research_context += f"- {r.title}: {r.snippet}\n"
                sources.append({"title": r.title, "url": r.url})
        except Exception as e:
            logger.warning("slide_tool_research_failed", error=str(e))

        # Phase 2: Generate outline via LLM with structured output
        research_section = ""
        if research_context:
            research_section = (
                "Research context (use this to ground your "
                "content with real data):\n" + research_context
            )

        prompt = f"""Create a complete, content-rich presentation for: "{topic}"

Number of slides: {num_slides}
Style: {style}
{f"Additional requirements: {additional_context}" if additional_context else ""}
{research_section}

Available layouts: title_slide, section_header, content, two_column, blank
- Start with title_slide, end with summary
- Write substantive, presentation-ready content — not just outlines
- For each content slide, write 3-6 detailed bullet points (1-2 sentences each)
- Include speaker notes with talking points on every content slide
- Include image_prompt on slides where a visual would add value
- Ensure exactly {num_slides} slides"""

        from app.ai.model_tiers import ModelTier

        llm = llm_service.get_llm_for_tier(ModelTier.PRO)
        structured_llm = llm.with_structured_output(SlideOutlineSchema)
        outline: SlideOutlineSchema = await structured_llm.ainvoke(prompt)

        deck_title = outline.title or topic
        raw_slides = outline.slides

        # Build SlideDeck
        from app.services.pptx_gen import SlideElement, SlideSpec

        theme = STYLE_THEMES.get(style, STYLE_THEMES["professional"])
        slides = []
        image_prompts: dict[int, str] = {}
        for idx, s in enumerate(raw_slides):
            elements = [
                SlideElement(
                    type=el.type or "text",
                    content=el.content or "",
                )
                for el in s.elements
            ]
            slides.append(
                SlideSpec(
                    layout=s.layout or "content",
                    title=s.title or "",
                    subtitle=s.subtitle,
                    elements=elements,
                    notes=s.notes,
                )
            )
            if s.image_prompt:
                image_prompts[idx] = s.image_prompt

        deck = SlideDeck(title=deck_title, theme=theme, slides=slides)

        # Phase 2.5: Generate images if requested
        if include_images and image_prompts:
            from app.ai.image import image_generation_service

            prompts_to_generate = list(image_prompts.items())[:4]
            for slide_idx, prompt_text in prompts_to_generate:
                try:
                    img_results = await image_generation_service.generate_image(
                        prompt=prompt_text,
                        size="1792x1024",
                        n=1,
                    )
                    if img_results and img_results[0].base64_data:
                        data_uri = f"data:image/png;base64,{img_results[0].base64_data}"

                        # Save to storage for preview URL
                        preview_url = ""
                        if user_id:
                            try:
                                import base64 as b64mod

                                image_bytes = b64mod.b64decode(img_results[0].base64_data)
                                storage_result = await file_storage_service.save_generated_image(
                                    image_data=image_bytes,
                                    user_id=user_id,
                                    content_type="image/png",
                                    metadata={"type": "slide_image", "slide_index": slide_idx},
                                )
                                preview_url = storage_result["url"]
                            except Exception as e:
                                logger.warning("slide_image_storage_failed", error=str(e))

                        deck.slides[slide_idx].elements.append(
                            SlideElement(
                                type="image",
                                content=data_uri,
                                style={"preview_url": preview_url},
                            )
                        )
                        logger.info(
                            "slide_tool_image_generated",
                            slide_index=slide_idx,
                            prompt=prompt_text[:60],
                        )
                except Exception as e:
                    logger.warning(
                        "slide_tool_image_generation_failed",
                        slide_index=slide_idx,
                        error=str(e),
                    )

        # Phase 3: Generate PPTX
        pptx_bytes = pptx_generation_service.generate_pptx(deck)

        # Build slide outline for frontend preview
        slide_outline = [
            {
                "layout": s.layout or "content",
                "title": s.title or "",
                "subtitle": s.subtitle,
                "elements": [
                    {
                        "type": el.type,
                        "content": (
                            el.style.get("preview_url", "")
                            if el.type == "image"
                            else el.content
                        ),
                    }
                    for el in s.elements
                    if el.type == "text"
                    or (el.type == "image" and el.style.get("preview_url"))
                ],
                "notes": s.notes,
            }
            for s in deck.slides
        ]

        result = {
            "success": True,
            "title": deck_title,
            "slide_count": len(slides),
            "sources": sources,
            "slide_outline": slide_outline,
        }

        # Save to storage
        if user_id:
            try:
                storage_result = await file_storage_service.save_generated_image(
                    image_data=pptx_bytes,
                    user_id=user_id,
                    content_type="application/vnd.openxmlformats-officedocument.presentationml.presentation",
                    metadata={
                        "type": "pptx",
                        "title": deck_title,
                        "slide_count": len(slides),
                    },
                )
                result["download_url"] = storage_result["url"]
                result["storage_key"] = storage_result["storage_key"]
                logger.info(
                    "slides_saved_to_storage",
                    storage_key=storage_result["storage_key"],
                    user_id=user_id,
                )
            except Exception as e:
                logger.error("slides_storage_failed", error=str(e))
                result["success"] = False
                result["error"] = f"Failed to save presentation: {e}"

        logger.info(
            "generate_slides_completed",
            title=deck_title,
            slide_count=len(slides),
        )

        return json.dumps(result)

    except Exception as e:
        logger.error("generate_slides_failed", topic=topic[:50], error=str(e))
        return json.dumps(
            {
                "success": False,
                "error": str(e),
                "topic": topic,
            }
        )
